version: 0.1.9.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PowerShellEdition: PowerShellCore
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PowerShellEdition: WindowsPowerShell

skip_commits:
  message: /doc update.*|updated readme.*|update readme.*|update changelog.*|update changelog.*s/
build: off

# Kick off the CI/CD pipeline
test_script:
  - ps:   if ($env:PowerShellEdition -eq 'WindowsPowerShell') { . .\build.ps1 -Bootstrap -Task Test, UploadTestResults }
  - pwsh: if ($env:PowerShellEdition -eq 'PowerShellCore')    { . .\build.ps1 -Bootstrap -Task Test, UploadTestResults }
